variables:
  VLC30_IMAGE: registry.videolan.org/medialibrary-3.0:20231017192545
  VLC40_IMAGE: registry.videolan.org/medialibrary-4.0:20231017192545

.common_build:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "$CI_DEFAULT_BRANCH@videolan/libvlcpp"'
  tags:
    - docker
    - amd64
  script:
    - export CXXFLAGS="-Werror" # Mainly to fail on deprecation errors.
    - meson setup build -Dexamples=enabled -Dtests=enabled
    - meson compile -C build
    - meson test -C build

continuous_build_4.0:
  extends: .common_build
  image: $VLC40_IMAGE

continuous_build_3.0:
  extends: .common_build
  image: $VLC30_IMAGE

